### ISSUE TITLE
Add a project license

### ISSUE THREAD

**Issue by Calinou** [YukkiTimmy/Tilemap2Tileset#2]
The repository currently doesn't seem to contain any formal license. While there is an informal notice in the README, it would be better to use an established open source license to guarantee that users can safely use this legally. Could you add a license, please? See [Choose a License](https://choosealicense.com/) for more information :slightly_smiling_face:

**Comment by YukkiTimmy** [comment]
Added a MIT License! Thanks for your suggestion!
